// <auto-generated />
using System;
using MVCBasico_ReservaJuego.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCBasico_ReservaJuego.Migrations
{
    [DbContext(typeof(ReservaDatabaseContext))]
    partial class ReservaDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCBasico_ReservaJuego.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MVCBasico_ReservaJuego.Models.Juego", b =>
                {
                    b.Property<int>("IdJuego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJuego"));

                    b.Property<int>("CantFichas")
                        .HasColumnType("int");

                    b.Property<int>("CantJugadoresMax")
                        .HasColumnType("int");

                    b.Property<int>("CantJugadoresMin")
                        .HasColumnType("int");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int>("Dificultad")
                        .HasColumnType("int");

                    b.Property<int>("EdadJugadores")
                        .HasColumnType("int");

                    b.Property<string>("NombreJuego")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("IdJuego");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("MVCBasico_ReservaJuego.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                  /*  b.Property<int?>("ClienteIdCliente") //Antes ClienteId
                        .HasColumnType("int");
                  */

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                   /* b.Property<int>("JuegoIdJuego")
                        .HasColumnType("int");
                   */

                    b.Property<int?>("IdJuego")//Antes JuegoId
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdCliente");//Antes ClienteId

                    b.HasIndex("IdJuego");//Antes JuegoId

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("MVCBasico_ReservaJuego.Models.Reserva", b =>
                {
                    b.HasOne("MVCBasico_ReservaJuego.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")//Antes ClienteId
                        .OnDelete(DeleteBehavior.Cascade)
                       .IsRequired();


                    b.HasOne("MVCBasico_ReservaJuego.Models.Juego", "Juego")
                        .WithMany()
                        .HasForeignKey("IdJuego")//Antes JuegoId
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Juego");
                });
#pragma warning restore 612, 618
        }
    }
}
